### ISSUE TITLE
Add support for jsx

### ISSUE THREAD

**Issue by luthv** [xabikos/vscode-javascript#2]
Currently the snippets are only working in js files, adding "javascriptreact" in the package.json should add support for jsx files. Although for some reason we have to press ctrl+space to trigger the intellisense in jsx files while in js files the suggestion will popup immediately as you type.

**Comment by xabikos** [comment]
In order to have these snippets available in jsx files you need to install the [Reactjs code snippets](https://marketplace.visualstudio.com/items/xabikos.ReactSnippets). There you will also find that I have added a note about the behavior of intellisnse you described. Hopefully it will be fixed in the coming version of Code.

**Comment by luthv** [comment]
ah I must have missed it, thanks for your great work on these extensions.

**Comment by xabikos** [comment]
I didn't know that a new version was available and indeed solves the intellisense issue. Thanks @luthv
