### ISSUE TITLE
Extension Host Failures Due to extension 

### ISSUE THREAD

**Issue by haugerbr** [xabikos/vscode-javascript#64]
![image](https://user-images.githubusercontent.com/660975/62254721-1f763500-b3af-11e9-9a21-3119dd8052d5.png)

**Comment by haugerbr** [comment]
It appears that in my case this is because Vue isn't one of the language options I have.

**Comment by xabikos** [comment]
@haugerbr could you please verify that this is still reported as error? I uninstall the corresponding extension, [Vetur](https://github.com/vuejs/vetur) which adds support for the identifier and didn't see any error. 

The problem is that to have the snippets available in vue files we need this configuration. We discussed this already in #49

**Comment by haugerbr** [comment]
I'll close this for now since they may have fixed this in the VSCode side. I would suggest you open a bug on the VSCode repo though if you keep having users reporting this since otherwise they most likely will uninstall the extension like I did.
