### ISSUE TITLE
JS suggest not working In with statement

### ISSUE THREAD

**Issue by younggeun0** [xabikos/vscode-javascript#71]
Hi
I'm using 'with' keyword for including my js functions. But in with statement block JS suggest is not working

with(express) {
  statement
  // I can't have a JS suggest here
}

**Comment by jyzhao** [comment]
+1
JS intellisense not working in code block

**Comment by xabikos** [comment]
@younggeun0 as I am not familiar with `with` statement could you give a bit more information?

I don't see why the snippets shouldn't appear only inside a `with` statement. Outside of this block snippets are available as usual? If yes this is most likely an issue with the editor itself rather than snippets. Snippets are becoming available based on language.

**Comment by younggeun0** [comment]
@xabikos Thanks for answering. I created an issue about this on VS Code Project too. They said `with` statement is deprecated so that they wouldn't fix it. So I close this issue.
